server:
  port: 7000

spring:
  #sleuth链路追踪配置
  sleuth:
    #启用链路追踪
    enabled: true
    #追踪系统是否支持在一个客户端和服务端之间分享一个spanID
    supports-join: true
    #是否生成128位追踪ID
    trace-id128: true
    #在流程外传播的行李列表
    baggage-keys:
    #在进程中引用的字段列表与在线程中引用的字段列表相同
    propagation-keys:
    #启用注解
    annotation:
      enabled: true
    #http啥啥啥
    http:
      enabled: true
      #使用传统的sleuth方法，而不是brave
      legacy:
        enabled: true
    #日志配置
    log:
      slf4j:
        enabled: true
    #异步执行器配置
    async:
      configurer:
        enabled: true
      enabled: true
    feign:
      enabled: true
      processor:
        enabled: true
    #断路器策略启用
    hystrix:
      strategy:
        enabled: true
    #集成配置
    integration:
      enabled: true
      #channel匹配模式
      patterns:
      #集成websocket也不知道干啥
      websockets:
        enabled: true
    keys:
      http:
        headers:
        prefix:
    #消息服务器配置
    messaging:
      enabled: true
      #kafka配置
      kafka:
        enabled: false
        remote-service-name:
      #rabbit配置
      rabbit:
        enabled: true
        #这是配置啥
        remote-service-name:
    #Opentracing配置，不知道干啥用
    opentracing:
      enabled: true
    #啥玩意？
    rxjava:
      schedulers:
        hook:
          enabled: true
        ignoredthreads:
    sampler:
      #链路信息采样率，过高会影响性能
      probability: 0.1
    #调度配置
    scheduled:
      enabled: true
      skip-pattern:
    #web配置
    web:
      enabled: true
      #应跳过追踪的URL，使用默认配置
      #skip-pattern:
      #额外的应该跳过追踪的模式，啥玩意？
      #additional-skip-pattern:
      #启用拦截器注入到RestTemplate中
      client:
        enabled: true
    #当使用zuul时，启用span信息传播
    zuul:
      enabled: true
  zipkin:
    #是否启用
    enabled: true
    #zipkin地址
    base-url: http://localhost:9411
    #是否通过服务发现查找zipkin服务地址
    discovery-client-enabled: false
    #发送类型，可以使用rabbit和kafka消息服务器
    sender:
      type: web
    #是否开启压缩
    compression:
      enabled: false
    #编码
    encoder: json_v1
    locator:
      discovery:
        enabled: true
    message-timeout: 1
    service:
      name:





