#admin服务短裤8000
server:
  port: 8000

spring:
  #安全配置
  security:
    user:
      name: admin
      password: 123456
  boot:
    #admin配置
    admin:
      #上下文路径
      context-path: /admin
      #服务发现，貌似启用服务发现后，不需要客户端配置，就可以服务管理
      discovery:
        #启用
        enabled: true
        converter:
          #健康端点路径
          health-endpoint-path: health
          #端点上下文路径
          management-context-path: /actuator
        #忽略的服务，目前有安全控制的服务的端点都访问不到，关闭安全控制暂时不合适
        ignored-services: eureka-service,admin-service
        #包含的服务
        services: '*'
      hazelcast:
        enabled: false
        event-store:
      instance-proxy:
        ignored-headers:
      metadata-keys-to-sanitize:
      monitor:
        connect-timeout:
        period:
        read-timeout:
        status-lifetime:
      notify:
        hipchat:
          enabled: false
          auth-token:
          description:
          ignore-changes:
          notify: true
          room-id:
          url:
        letschat:
          enabled: false
          ignore-changes:
          message:
          room:
          token:
          url:
          username:
        mail:
          enabled: false
          additional-properties:
          base-url:
          cc:
          from:
          ignore-changes:
          template:
          to:
        ms-teams:
          enabled: false
          de-registered-title:
          deregister-activity-subtitle-pattern:
          ignore-changes:
          message-summary:
          register-activity-subtitle-pattern:
          registered-title:
          status-activity-subtitle-pattern:
          status-changed-title:
          theme-color:
          webhook-url:
        opsgenie:
          enabled: false
          actions:
          api-key:
          entity:
          ignore-changes:
          source:
          tags:
          user:
        pagerduty:
          enabled: false
          client:
          client-url:
          description:
          ignore-changes:
          service-key:
          url:
        slack:
          enabled: false
          channel:
          icon:
          ignore-changes:
          message:
          username:
          webhook-url:
        telegram:
          enabled: false
          api-url:
          auth-token:
          chat-id:
          disable-notify: true
          ignore-changes:
          parse-mode:
      probed-endpoints:
      #视图配置
      ui:
        #页面标题，使用默认配置
        #title: Spring Boot Admin
        #商标，使用默认配置
        #brand: "<img src=\"assets/img/icon-spring-boot-admin.svg\"><span>Spring Boot Admin</span>"
        cache-templates: true
        cache:
          max-age: 3600s
          no-cache: true
          no-store: true
        #资源定位，使用默认配置
        #extension-resource-locations:
        #resource-locations:
        #template-location:



