#服务中心端口9999
server:
  port: 9999

spring:
  profiles:
    active: dev

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
          defaultZone: http://localhost:9999/eureka
  server:
    a-s-g-cache-expiry-timeout-ms: 1000
    a-s-g-query-timeout-ms: 1000
    a-s-g-update-interval-ms: 1000
    batch-replication: true
  eureka:
    #启用服务中心控制面板
    dashboard:
      enabled: true


