server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    connection-timeout: 3000
    login-timeout: 3000
    max-active: 20
    max-idle: 10
    max-lifetime: 20000
    maximum-pool-size: 30
    min-idle: 10
    sql-script-encoding: utf-8
    test-on-connect: true
    
mybatis:
  configuration:
    log-prefix: mybatis
  