#服务中心端口9999
server:
  port: 9998

eureka:
  client:
    service-url:
      defaultZone: http://user:peer1@localhost:9999/eureka,http://user:peer3@localhost:9997/eureka

spring:
  security:
    user:
      name: user
      password: peer2