server:
  port: 9997

eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      defaultZone: http://user:peer2@peer2:9998/eureka,http://user:peer1@peer1:9999/eureka

spring:
  security:
    user:
      name: user
      password: peer3