server:
  port: 9997

eureka:
  client:
    service-url:
      defaultZone: http://user:peer2@localhost:9998/eureka,http://user:peer1@localhost:9999/eureka

spring:
  security:
    user:
      name: user
      password: peer3