
#因为配置中心也要注册为服务的缘故，所以服务中心的配置文件没有从配置中心获取
spring:
  application:
    name: eureka-service
  profiles:
      active: peer3
  #eureka集群化后，复制请求出错，编码也不行
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

eureka:
  #服务中心配置
  server:
    batch-replication: true
    a-s-g-query-timeout-ms: 1000
    a-s-g-update-interval-ms: 1000
    a-s-g-cache-expiry-timeout-ms: 1000
    #禁用自我保护，保证及时踢出不可用服务
    enable-self-preservation: true
    #复制请求压缩，开启就报错，压缩没问题，但是好像解压不行
    enable-replicated-request-compression: false
    renewal-percent-threshold: 0.85
  #启用服务中心控制面板
  dashboard:
    enabled: true
  #服务客户端配置，服务url、注册实例id等
  #一组服务首先的标识是application name，然后每个服务有自己的instance-id来标识自己
  client:
    #服务中心自注册时，如果配置抓取注册表，则会有一开始请求失败的现象
    #因为一开始注册中心未启动，注册表获取不到
    #而注册自己的行为是在注册中心启动之后进行的，不受影响
    fetch-registry: true
    register-with-eureka: true
    eureka-server-connect-timeout-seconds: 20
    eureka-connection-idle-timeout-seconds: 20
  #向服务中心注册的服务实例属性
  instance:
    appname: eureka-service
    app-group-name: admin
    prefer-ip-address: false
    #这个ip-address如果配置为ipAddress就不行
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

logging:
  level:
    root: info
