#服务中心端口9999
server:
  port: 9998

eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://user:peer1@peer1:9999/eureka,http://user:peer3@peer3:9997/eureka

spring:
  security:
    user:
      name: user
      password: peer2