spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/crayon-shin-chan/taotao-config.git
          default-label: master
          clone-on-start: false
          refresh-rate: 360

server:
  port: 8888



