spring:
  application:
    name: config-service
  profiles:
  #spring cloud通过不同的profile来控制实际的配置仓库类型：
  #git、native、subversion、vault、jdbc、composite等六种仓库类型
  #默认为git配置存储库
      active: native
  cloud:
    config:
    #是否允许本地属性覆盖配置服务器属性
      allow-override: false
      server:
        #指定配置服务是否应该使用从远程存储库中获取的属性初始化自身环境
        bootstrap: false
        #资源路径的前缀
        prefix:
        #请求中指定应用程序不存在时，是否返回404
        accept-empty: true
        #当请求未指定标签时，使用的默认标签,profile,应用名称
        default-label: master
        default-profile: dev
        default-application-name: application
        #本地文件系统仓库配置
        native:
          order: 1
          version: 1.0
          default-label: master
          fail-on-error: true
          add-label-locations: false
          #搜索配置文件的位置
          search-locations: classpath:/config/
  #安全配置，默认为开启Http Basic认证
  security:
    user:
      name: user
      password: 123456


#配置中心端口8888
server:
  port: 8888




